# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev_sayeed ]
  pull_request:
    branches: [ dev_sayeed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  automerge:
   runs-on: ubuntu-latest
   steps:
     - name: automerge
       uses: "sayeedap/automerge-action@v0.14.3"
